name: Docker Image CI

on:
  pull_request:
    branches: [ "*" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ vars.REPOSITORY_VAR }}:$(date +%s) --platform=linux/amd64
